api:
  autodiscoveryId: "123456"  

http:
 listener:
  host: "0.0.0.0"
  port: "8081"
  timeout: "30000"
 request:
  host: "sb-iewc-sapi.us-e2.cloudhub.io"
  timeout: "30000"
  port: ""
  path: "/api/salesdoc_output" 
  
https:
  host: "0.0.0.0"
  port: "8082"